### ISSUE TITLE
Sequence contains no elements exception.

### ISSUE THREAD

**Issue by ikeough** [hypar-io/IFC-gen#50]
When parsing a STEP file written by IFC-gen, we get the following:
```
Error Message:
 System.Exception : Constructor parsing exception at id 2469 : IFCTRIMMEDCURVE(#2468,(IFCPARAMETERVALUE(270)),(IFCPARAMETERVALUE(0.0)),.T.,.PARAMETER.) : Sequence contains no elements :    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at STEP.STEPListener.GetConstructorForType(Type required, List`1& ctorChain, Type fromSTEP) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 111
   at STEP.STEPListener.CreateIfcTypeOrUseConstructorParameterTypeToConstruct[TValue](Type typeToConstruct, TValue value) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 342
   at STEP.STEPListener.ParseInt(Type t, String value) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 320
   at STEP.STEPListener.ParseConstructor(Int32 id, ConstructorContext context, Type ifcType) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 254
   at STEP.STEPListener.ParseCollection(Type t, CollectionContext value) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 453
   at STEP.STEPListener.ParseConstructor(Int32 id, ConstructorContext context, Type ifcType) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 218
   at STEP.STEPListener.EnterConstructor(ConstructorContext context) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 96.
Stack Trace:
   at STEP.STEPListener.EnterConstructor(ConstructorContext context) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/STEP/STEPListener.cs:line 101
   at STEP.STEPParser.ConstructorContext.EnterRule(IParseTreeListener listener) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/antlr/STEPParser.cs:line 358
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at IFC.Model..ctor(String STEPfilePath, IDictionary`2 storage, IList`1& errors) in /Users/ikeough/Documents/IFC-gen/lang/csharp/src/Model.cs:line 169
   at IFC.Tests.STEP.DeserializeFromSTEP(String modelPath, Int32 expectedInstanceCount, Int32 expectedErrorCount) in /Users/ikeough/Documents/IFC-gen/lang/csharp/tests/STEP.cs:line 46
```

Original:
```
#4568= IFCTRIMMEDCURVE(#4567,(IFCPARAMETERVALUE(269.999999999996)),(IFCPARAMETERVALUE(0.)),.T.,.PARAMETER.);
```
Generated:
```
#2469 = IFCTRIMMEDCURVE(#2468, (IFCPARAMETERVALUE(270)), (IFCPARAMETERVALUE(0.0)), .T., .PARAMETER.);
```

**Comment by ikeough** [comment]
This is happening because 269.999... is being rounded to 270 and is then being treated as an int.

**Comment by ikeough** [comment]
This is because we do `return value.ToString("G9", CultureInfo.InvariantCulture);` and the number 269.999999999996 is rounded to 270.
