### ISSUE TITLE
Run "make ts" on an M1 Pro

### ISSUE THREAD

**Issue by sbstnkll** [hypar-io/IFC-gen#74]
I have problems running "make ts" on an M1 pro. All the dependencies have been installed. I get the following output:

`(base) sebastiankulle@Sebastians-MacBook-Pro IFC-gen % make ts
dotnet build ./src/IFC-gen.csproj
MSBuild version 17.6.3+07e294721 for .NET
  Determining projects to restore...
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
  All projects are up-to-date for restore.
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressParser.cs(36,22): warning CS3021: 'ExpressParser' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressBaseListener.cs(37,22): warning CS3021: 'ExpressBaseListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressLexer.cs(33,22): warning CS3021: 'ExpressLexer' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressListener.cs(33,18): warning CS3021: 'IExpressListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/Generators/ProtobufGenerator.cs(54,53): warning CS0162: Unreachable code detected [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
  IFC-gen -> /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/bin/Debug/netcoreapp2.0/IFC-gen.dll

Build succeeded.

/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressParser.cs(36,22): warning CS3021: 'ExpressParser' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressBaseListener.cs(37,22): warning CS3021: 'ExpressBaseListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressLexer.cs(33,22): warning CS3021: 'ExpressLexer' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressListener.cs(33,18): warning CS3021: 'IExpressListener' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/Generators/ProtobufGenerator.cs(54,53): warning CS0162: Unreachable code detected [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
    10 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.62
dotnet run -p ./src/IFC-gen.csproj -e /Users/sebastiankulle/Documents/GitHub/IFC-gen/schemas/IFC.exp -l ts -o ./lang/typescript/src
Warning NETSDK1174: The abbreviation of -p for --project is deprecated. Please use --project.
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
/usr/local/share/dotnet/sdk/7.0.304/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj]
/Users/sebastiankulle/Documents/GitHub/IFC-gen/src/IFC-gen.csproj : warning NU1701: Package 'NDesk.Options 0.2.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at IFC4.Generators.TypescriptGenerator.AttributeDataType(Boolean isCollection, Int32 rank, String type, Boolean isGeneric) in /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/Generators/TypescriptGenerator.cs:line 57
   at Express.TypeReference.get_Type() in /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/TypeData.cs:line 41
   at Express.ExpressListener.EnterEntityDecl(EntityDeclContext context) in /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/ExpressListener.cs:line 168
   at Express.ExpressParser.EntityDeclContext.EnterRule(IParseTreeListener listener) in /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/antlr/ExpressParser.cs:line 2958
   at Antlr4.Runtime.Tree.ParseTreeWalker.EnterRule(IParseTreeListener listener, IRuleNode r)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at Antlr4.Runtime.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at IFC.Generate.Program.Main(String[] args) in /Users/sebastiankulle/Documents/GitHub/IFC-gen/src/Program.cs:line 65
make: *** [ts] Error 134`

**Comment by sbstnkll** [comment]
Some more info on the dependencies:

```bash
(base) sebastiankulle@Sebastians-MacBook-Pro IFC-gen % dotnet --list-sdks                                          
6.0.410 [/usr/local/share/dotnet/sdk]
7.0.304 [/usr/local/share/dotnet/sdk]

(base) sebastiankulle@Sebastians-MacBook-Pro IFC-gen % dotnet --list-runtimes  
Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by ikeough** [comment]
It seems like you're running the Typescript generator. I haven't played with that in years, so it's possible that there's a breakage there.

**Comment by ikeough** [comment]
I just updated everything to use the newest version of antlr and net7.0. It definitely fixes a couple of the errors you've shown above. It works on my macbook M2 as well. Give it another go and LMK if it works for you.

I tested this with graph-ql a long time ago and it worked. Unfortunately it was an afternoon experiment and I didn't save it in a branch. GraphQL is probably more advanced then it was when I tried that experiment, so it might not matter anyway.
